# Generated by Django 4.2.11 on 2024-04-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('open_time', models.DateTimeField(verbose_name='open time')),
                ('open_price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('low_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('close_time', models.DateTimeField(verbose_name='close time')),
                ('number_of_trades', models.IntegerField(default=0)),
            ],
        ),
    ]
