# Generated by Django 4.2.11 on 2024-04-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_symbols_alter_klineentry_symbol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symbols',
            new_name='Symbol',
        ),
    ]
